// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// makeExtPtr
SEXP makeExtPtr(SEXP func, SEXP path);
RcppExport SEXP _testPackage_makeExtPtr(SEXP funcSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    Rcpp::traits::input_parameter< SEXP >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(makeExtPtr(func, path));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_testPackage_makeExtPtr", (DL_FUNC) &_testPackage_makeExtPtr, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_testPackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
